plugins:
  procourse_convertkit_enabled:
    default: false
    client: false
  procourse_convertkit_api_key:
    default: ""
    client: false
  procourse_convertkit_form_id:
    default: ""
    client: false
  procourse_convertkit_add_group:
    default: false
    client: false
  procourse_convertkit_group:
    default: ""
    client: false
  procourse_convertkit_tag:
    default: ""
    client: false
